// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwoleucbakneoiyctwyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3b2xldWNiYWtuZW9peWN0d3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2OTU0NTgsImV4cCI6MjA3NDI3MTQ1OH0.g5tO4KgX1_nnGRAObnUy9OgGcQk4lnXBXdI0gQY5FeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});